name: CI

"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Only do Docker builds of ticket branches and tagged releases.
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/tickets/')

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        id: depend
        run: pip install -r requirements.txt
        working-directory: ./tap-schema

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run the build
        id: build-tap-schema
        run: ./build-all
        working-directory: ./tap-schema

      - name: Build datalink release
        id: build-datalink
        run: ./build
        working-directory: ./datalink

      - name: Release Datalink
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: datalink/datalink-snippets.zip
