name: Felis Linter

"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Only do Docker builds of ticket branches and tagged releases.
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/tickets/')

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        id: depend
        run: pip install -r requirements.txt
        working-directory: ./tap-schema

      - name: Validate YAML files
        id: validate-yaml
        run: ./validator ../yml/*.yaml
        working-directory: ./tap-schema
