name: Validate SDM schemas using Felis

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'lsst-felis @ git+https://github.com/lsst/felis@main'

      - name: Validate YAML files
        run: felis validate --check-redundant-datatypes ./yml/*.yaml
